#include "../headers/kmlExport.h"
#include "../headers/mode.h"
#include <cstdio>
#include <cstring>
#include <ctime>

// ------------------------------------------------------------
// Get color for transport mode (KML format: aabbggrr)
// ------------------------------------------------------------
const char* getTransportModeColor(TransportMode transportMode) {
    switch (transportMode) {
        case TRANSPORT_CAR:
            return "ff0000ff";      // Red
        case TRANSPORT_METRO:
            return "ffff0000";      // Blue
        case TRANSPORT_BIKOLPO:
            return "ff00ff00";      // Green
        case TRANSPORT_UTTARA:
            return "ff00ffff";      // Yellow
        case TRANSPORT_WALK:
            return "ff808080";      // Gray
        default:
            return "ffffffff";      // White
    }
}

// ------------------------------------------------------------
// Get style ID for transport mode
// ------------------------------------------------------------
const char* getTransportModeStyle(TransportMode transportMode) {
    switch (transportMode) {
        case TRANSPORT_CAR:
            return "carStyle";
        case TRANSPORT_METRO:
            return "metroStyle";
        case TRANSPORT_BIKOLPO:
            return "bikolpoStyle";
        case TRANSPORT_UTTARA:
            return "uttaraStyle";
        case TRANSPORT_WALK:
            return "walkStyle";
        default:
            return "defaultStyle";
    }
}

// ------------------------------------------------------------
// Write KML header with styles
// ------------------------------------------------------------
static void writeKMLHeader(FILE* kmlFile, const char* documentName) {
    fprintf(kmlFile, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    fprintf(kmlFile, "<kml xmlns=\"http://www.opengis.net/kml/2.2\">\n");
    fprintf(kmlFile, "<Document>\n");
    fprintf(kmlFile, "  <name>%s</name>\n", documentName);
    fprintf(kmlFile, "  <description>Generated by Dhaka Transportation Route Finder</description>\n\n");
    
    // Define styles for each transport mode
    fprintf(kmlFile, "  <Style id=\"carStyle\">\n");
    fprintf(kmlFile, "    <LineStyle>\n");
    fprintf(kmlFile, "      <color>%s</color>\n", getTransportModeColor(TRANSPORT_CAR));
    fprintf(kmlFile, "      <width>4</width>\n");
    fprintf(kmlFile, "    </LineStyle>\n");
    fprintf(kmlFile, "  </Style>\n\n");
    
    fprintf(kmlFile, "  <Style id=\"metroStyle\">\n");
    fprintf(kmlFile, "    <LineStyle>\n");
    fprintf(kmlFile, "      <color>%s</color>\n", getTransportModeColor(TRANSPORT_METRO));
    fprintf(kmlFile, "      <width>4</width>\n");
    fprintf(kmlFile, "    </LineStyle>\n");
    fprintf(kmlFile, "  </Style>\n\n");
    
    fprintf(kmlFile, "  <Style id=\"bikolpoStyle\">\n");
    fprintf(kmlFile, "    <LineStyle>\n");
    fprintf(kmlFile, "      <color>%s</color>\n", getTransportModeColor(TRANSPORT_BIKOLPO));
    fprintf(kmlFile, "      <width>4</width>\n");
    fprintf(kmlFile, "    </LineStyle>\n");
    fprintf(kmlFile, "  </Style>\n\n");
    
    fprintf(kmlFile, "  <Style id=\"uttaraStyle\">\n");
    fprintf(kmlFile, "    <LineStyle>\n");
    fprintf(kmlFile, "      <color>%s</color>\n", getTransportModeColor(TRANSPORT_UTTARA));
    fprintf(kmlFile, "      <width>4</width>\n");
    fprintf(kmlFile, "    </LineStyle>\n");
    fprintf(kmlFile, "  </Style>\n\n");
    
    fprintf(kmlFile, "  <Style id=\"walkStyle\">\n");
    fprintf(kmlFile, "    <LineStyle>\n");
    fprintf(kmlFile, "      <color>%s</color>\n", getTransportModeColor(TRANSPORT_WALK));
    fprintf(kmlFile, "      <width>2</width>\n");
    fprintf(kmlFile, "    </LineStyle>\n");
    fprintf(kmlFile, "  </Style>\n\n");
}

// ------------------------------------------------------------
// Write KML footer
// ------------------------------------------------------------
static void writeKMLFooter(FILE* kmlFile) {
    fprintf(kmlFile, "</Document>\n");
    fprintf(kmlFile, "</kml>\n");
}

// ------------------------------------------------------------
// Export a specific route to KML file
// ------------------------------------------------------------
void exportRouteToKML(const char* outputFilePath, 
                      int routePath[], 
                      int routeLength,
                      int routeConnections[],
                      const char* routeName,
                      const char* routeDescription) {
    FILE* kmlFile = fopen(outputFilePath, "w");
    if (!kmlFile) {
        printf("Error: Could not create KML file %s\n", outputFilePath);
        return;
    }
    
    writeKMLHeader(kmlFile, routeName);
    
    fprintf(kmlFile, "  <Folder>\n");
    fprintf(kmlFile, "    <name>%s</name>\n", routeName);
    fprintf(kmlFile, "    <description>%s</description>\n", routeDescription);
    
    // Write placemarks for each segment
    for (int segmentIdx = routeLength - 1; segmentIdx > 0; segmentIdx--) {
        int originVertex = routePath[segmentIdx];
        int targetVertex = routePath[segmentIdx - 1];
        int connectionIndex = routeConnections[segmentIdx - 1];
        
        TransportMode segmentMode = TRANSPORT_CAR;
        double segmentDistance = 0.0;
        
        if (connectionIndex >= 0 && connectionIndex < connectionCount) {
            segmentMode = connectionArray[connectionIndex].transportMode;
            segmentDistance = connectionArray[connectionIndex].distance;
        }
        
        fprintf(kmlFile, "    <Placemark>\n");
        fprintf(kmlFile, "      <name>Segment %d: %s to %s</name>\n", 
                routeLength - segmentIdx,
                vertexArray[originVertex].name,
                vertexArray[targetVertex].name);
        fprintf(kmlFile, "      <description>Mode: %s, Distance: %.3f km</description>\n",
                retrieveTransportTypeName(segmentMode), segmentDistance);
        fprintf(kmlFile, "      <styleUrl>#%s</styleUrl>\n", getTransportModeStyle(segmentMode));
        fprintf(kmlFile, "      <LineString>\n");
        fprintf(kmlFile, "        <coordinates>\n");
        fprintf(kmlFile, "          %.6f,%.6f,0\n", 
                vertexArray[originVertex].lon, vertexArray[originVertex].lat);
        fprintf(kmlFile, "          %.6f,%.6f,0\n", 
                vertexArray[targetVertex].lon, vertexArray[targetVertex].lat);
        fprintf(kmlFile, "        </coordinates>\n");
        fprintf(kmlFile, "      </LineString>\n");
        fprintf(kmlFile, "    </Placemark>\n\n");
    }
    
    // Add start and end markers
    fprintf(kmlFile, "    <Placemark>\n");
    fprintf(kmlFile, "      <name>Start: %s</name>\n", vertexArray[routePath[routeLength - 1]].name);
    fprintf(kmlFile, "      <Point>\n");
    fprintf(kmlFile, "        <coordinates>%.6f,%.6f,0</coordinates>\n",
            vertexArray[routePath[routeLength - 1]].lon,
            vertexArray[routePath[routeLength - 1]].lat);
    fprintf(kmlFile, "      </Point>\n");
    fprintf(kmlFile, "    </Placemark>\n\n");
    
    fprintf(kmlFile, "    <Placemark>\n");
    fprintf(kmlFile, "      <name>End: %s</name>\n", vertexArray[routePath[0]].name);
    fprintf(kmlFile, "      <Point>\n");
    fprintf(kmlFile, "        <coordinates>%.6f,%.6f,0</coordinates>\n",
            vertexArray[routePath[0]].lon,
            vertexArray[routePath[0]].lat);
    fprintf(kmlFile, "      </Point>\n");
    fprintf(kmlFile, "    </Placemark>\n");
    
    fprintf(kmlFile, "  </Folder>\n");
    
    writeKMLFooter(kmlFile);
    fclose(kmlFile);
    
    printf("✓ Route exported to KML: %s\n", outputFilePath);
}

// ------------------------------------------------------------
// Export entire network for a specific transport mode
// ------------------------------------------------------------
void exportNetworkToKML(const char* outputFilePath,
                        TransportMode filterMode,
                        const char* networkName) {
    FILE* kmlFile = fopen(outputFilePath, "w");
    if (!kmlFile) {
        printf("Error: Could not create KML file %s\n", outputFilePath);
        return;
    }
    
    writeKMLHeader(kmlFile, networkName);
    
    fprintf(kmlFile, "  <Folder>\n");
    fprintf(kmlFile, "    <name>%s Network</name>\n", retrieveTransportTypeName(filterMode));
    fprintf(kmlFile, "    <description>All connections for %s</description>\n", 
            retrieveTransportTypeName(filterMode));
    
    int exportedCount = 0;
    
    // Export all edges of this transport mode
    for (int edgeIdx = 0; edgeIdx < connectionCount; edgeIdx++) {
        if (connectionArray[edgeIdx].transportMode == filterMode) {
            int originVertex = connectionArray[edgeIdx].originVertex;
            int targetVertex = connectionArray[edgeIdx].targetVertex;
            
            fprintf(kmlFile, "    <Placemark>\n");
            fprintf(kmlFile, "      <name>%s to %s</name>\n",
                    vertexArray[originVertex].name,
                    vertexArray[targetVertex].name);
            fprintf(kmlFile, "      <description>Distance: %.3f km</description>\n",
                    connectionArray[edgeIdx].distance);
            fprintf(kmlFile, "      <styleUrl>#%s</styleUrl>\n", getTransportModeStyle(filterMode));
            fprintf(kmlFile, "      <LineString>\n");
            fprintf(kmlFile, "        <coordinates>\n");
            fprintf(kmlFile, "          %.6f,%.6f,0\n",
                    vertexArray[originVertex].lon, vertexArray[originVertex].lat);
            fprintf(kmlFile, "          %.6f,%.6f,0\n",
                    vertexArray[targetVertex].lon, vertexArray[targetVertex].lat);
            fprintf(kmlFile, "        </coordinates>\n");
            fprintf(kmlFile, "      </LineString>\n");
            fprintf(kmlFile, "    </Placemark>\n\n");
            
            exportedCount++;
        }
    }
    
    fprintf(kmlFile, "  </Folder>\n");
    
    writeKMLFooter(kmlFile);
    fclose(kmlFile);
    
    printf("✓ %s network exported to KML: %s (%d connections)\n", 
           retrieveTransportTypeName(filterMode), outputFilePath, exportedCount);
}

// ------------------------------------------------------------
// Export all networks to separate KML files
// ------------------------------------------------------------
void exportAllNetworksToKML(const char* outputDirectory) {
    char outputPath[512];
    
    printf("\n========================================\n");
    printf("  Exporting All Networks to KML\n");
    printf("========================================\n\n");
    
    // Export Car network
    snprintf(outputPath, sizeof(outputPath), "%s/car_network.kml", outputDirectory);
    exportNetworkToKML(outputPath, TRANSPORT_CAR, "Car Road Network");
    
    // Export Metro network
    snprintf(outputPath, sizeof(outputPath), "%s/metro_network.kml", outputDirectory);
    exportNetworkToKML(outputPath, TRANSPORT_METRO, "Metro Rail Network");
    
    // Export Bikolpo Bus network
    snprintf(outputPath, sizeof(outputPath), "%s/bikolpo_network.kml", outputDirectory);
    exportNetworkToKML(outputPath, TRANSPORT_BIKOLPO, "Bikolpo Bus Network");
    
    // Export Uttara Bus network
    snprintf(outputPath, sizeof(outputPath), "%s/uttara_network.kml", outputDirectory);
    exportNetworkToKML(outputPath, TRANSPORT_UTTARA, "Uttara Bus Network");
    
    printf("\n✓ All networks exported successfully!\n");
    printf("========================================\n");
}
